insert into TB_VEHICLE(LICENSE, COUNTRY, RISK_FACTOR, N_DOORS, FUEL_TYPE, POWER) values("GG 00 KK", "PT", 2.14, 3, "DIESEL", 188);
insert into TB_VEHICLE(LICENSE, COUNTRY, RISK_FACTOR, N_DOORS, FUEL_TYPE, POWER) values("GG 00 KK", "PE", 2.88, 3, "ELECTRIC", 188);
insert into TB_VEHICLE(LICENSE, COUNTRY, RISK_FACTOR, N_DOORS, FUEL_TYPE, POWER) values("AA 00 AA", "GE", 3.14, 3, "LPG", 188);
insert into TB_VEHICLE(LICENSE, COUNTRY, RISK_FACTOR, N_DOORS, FUEL_TYPE, POWER) values("GG 22 II", "UK", 20.14, 3, "NATURALGAS", 188);
insert into TB_VEHICLE(LICENSE, COUNTRY, RISK_FACTOR, N_DOORS, FUEL_TYPE, POWER) values("GG 00 PP", "US", 0.14, 3, "DIESEL", 188);